/* Additional record code for TwoTankController generated by the OpenModelica Compiler OpenModelica v1.27.1 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "TwoTankController_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

