# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=-municode $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"C:/Program Files/OpenModelica1.27.1-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.27.1-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=TwoTankController -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lryu -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.27.1-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.1-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.27.1-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.1-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.27.1-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lsz -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"D:/SpecAlive/cases/tank"
MAINFILE=TwoTankController.c
MAINOBJ=TwoTankController.o
CFILES=TwoTankController_functions.c TwoTankController_records.c \
TwoTankController_01exo.c TwoTankController_02nls.c TwoTankController_03lsy.c TwoTankController_04set.c TwoTankController_05evt.c TwoTankController_06inz.c TwoTankController_07dly.c \
TwoTankController_08bnd.c TwoTankController_09alg.c TwoTankController_10asr.c TwoTankController_11mix.c TwoTankController_12jac.c TwoTankController_13opt.c TwoTankController_14lnz.c \
TwoTankController_15syn.c TwoTankController_16dae.c TwoTankController_17inl.c TwoTankController_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) TwoTankController.makefile TwoTankController_literals.h TwoTankController_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that TwoTankController_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) TwoTankController_functions.h TwoTankController_literals.h $(OFILES)
	$(CC) -I. -o TwoTankController$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) TwoTankController_functions.h TwoTankController_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o TwoTankController$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f TwoTankController_records.o $(MAINOBJ)

bundle:
	@tar -cvf TwoTankController_Files.tar $(GENERATEDFILES)