/* Simulation code for TwoTankController generated by the OpenModelica Compiler OpenModelica v1.27.1 (64-bit). */
#if !defined(TwoTankController__MODEL_H)
#define TwoTankController__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "TwoTankController_functions.h"


extern void TwoTankController_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void TwoTankController_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int TwoTankController_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int TwoTankController_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int TwoTankController_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TwoTankController_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TwoTankController_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int TwoTankController_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int TwoTankController_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int TwoTankController_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int TwoTankController_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int TwoTankController_checkForAsserts(DATA *data, threadData_t *threadData);
extern int TwoTankController_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int TwoTankController_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int TwoTankController_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* TwoTankController_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* TwoTankController_relationDescription(int i);
extern void TwoTankController_function_initSample(DATA *data, threadData_t *threadData);
extern int TwoTankController_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoTankController_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoTankController_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoTankController_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoTankController_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoTankController_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoTankController_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoTankController_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoTankController_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* TwoTankController_linear_model_frame(void);
extern const char* TwoTankController_linear_model_datarecovery_frame(void);
extern int TwoTankController_mayer(DATA* data, modelica_real** res, short *);
extern int TwoTankController_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int TwoTankController_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int TwoTankController_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int TwoTankController_setInputData(DATA *data, const modelica_boolean file);
extern int TwoTankController_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void TwoTankController_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void TwoTankController_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int TwoTankController_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void TwoTankController_read_simulation_info(SIMULATION_INFO* simulationData);
extern void TwoTankController_read_input_fmu(MODEL_DATA* modelData);
extern void TwoTankController_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int TwoTankController_inputNames(DATA* data, char ** names);
extern int TwoTankController_dataReconciliationInputNames(DATA* data, char ** names);
extern int TwoTankController_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int TwoTankController_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int TwoTankController_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int TwoTankController_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "TwoTankController_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(TwoTankController__MODEL_H) */


