"""Modelica emitter.

Renders the validated PlantModel as a runnable Modelica model (.mo): plant
parameters plus a one-day energy simulation with a clear-sky plane-of-array
irradiance profile, temperature-derated DC power, and inverter clipping. The
integrated AC energy over the day cross-checks the Python engine's specific
yield.

Run (with OpenModelica):
    omc  or  loadFile("PVPlant.mo"); simulate(PVPlant, stopTime=86400)
"""
from __future__ import annotations

from .schema import PlantModel
from .simulate import SimResult


def _safe_name(project: str) -> str:
    n = "".join(c if c.isalnum() else "_" for c in project).strip("_")
    if not n or not n[0].isalpha():
        n = "PVPlant_" + n
    return n


def to_modelica(m: PlantModel, sim: SimResult) -> str:
    name = _safe_name(m.project)
    e = sim.extras
    dc_kw = e["dc_kw"]
    ac_kw = e["ac_kw"]
    pr = e["pr"]
    # daily POA energy density (kWh/m2/day) implied by annual POA
    poa_day = sim.extras["poa_annual"] / 365.0

    return f"""model {name} "SpecAlive-generated plant model for {m.project}"
  // ---- constants ----
  constant Real pi = 3.141592653589793;
  constant Real dayLength = 86400.0 "s";

  // ---- design parameters (from validated PlantModel) ----
  parameter Integer nModules = {m.n_modules};
  parameter Real moduleWp = {m.module.wp} "Wp";
  parameter Integer modulesPerString = {m.modules_per_string};
  parameter Integer nStrings = {m.n_strings};
  parameter Integer nInverters = {m.n_inverters};
  parameter Real dcCapacityKW = {dc_kw} "kW";
  parameter Real acCapacityKW = {ac_kw} "kW";
  parameter Real dcAcRatio = {sim.m('dc_ac_ratio')};
  parameter Real performanceRatio = {pr};

  // clear-sky irradiance shape: peak 1.0 kW/m2 around solar noon
  parameter Real peakIrradiance = 1.0 "kW/m2";
  parameter Real sunrise = 6.0 "h";
  parameter Real sunset = 18.0 "h";

  // ---- variables ----
  Real hourOfDay "h";
  Real irradiance "plane-of-array, kW/m2";
  Real dcPower "kW";
  Real acPower "kW (after inverter clipping)";
  Real energyKWh(start = 0) "cumulative AC energy";

equation
  hourOfDay = (time / dayLength) * 24.0;

  // half-sine clear-sky profile between sunrise and sunset, else 0
  irradiance = if hourOfDay > sunrise and hourOfDay < sunset then
                 peakIrradiance * sin(pi * (hourOfDay - sunrise) / (sunset - sunrise))
               else 0.0;

  // DC power scales with irradiance and performance ratio
  dcPower = dcCapacityKW * irradiance * performanceRatio;

  // inverter clipping at AC nameplate
  acPower = min(dcPower, acCapacityKW);

  // integrate power (kW) over time (s) -> kWh
  der(energyKWh) = acPower / 3600.0;

annotation(
  experiment(StartTime = 0, StopTime = 86400, Interval = 600),
  Documentation(info = "<html>
    Generated by SpecAlive. Design POA ~ {poa_day:.2f} kWh/m2/day,
    expected specific yield ~ {sim.m('specific_yield_kwh_kwp'):.0f} kWh/kWp/yr.
    Simulate over one day (StopTime=86400 s); daily specific yield =
    energyKWh / dcCapacityKW.
  </html>"));
end {name};
"""
